# Generated by Django 5.1.4 on 2025-01-22 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='num',
            field=models.IntegerField(default=0),
        ),
    ]
