# Generated by Django 5.1.4 on 2025-01-22 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='num',
        ),
    ]
